# Generated by Django 4.1.1 on 2022-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="airport",
            constraint=models.UniqueConstraint(fields=("icao",), name="unique icao"),
        ),
        migrations.AddConstraint(
            model_name="pilot",
            constraint=models.UniqueConstraint(
                fields=("anac_code", "cpf"), name="unique anac code"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("cpf",), name="unique document"),
        ),
    ]
