# Generated by Django 4.1.1 on 2022-11-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="airline",
            constraint=models.UniqueConstraint(
                fields=("flight_identifier",), name="unique flight identifier"
            ),
        ),
    ]
