# Generated by Django 4.1.1 on 2022-11-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_airline_unique flight identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="origin_airport",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_airports",
                to="Main.airport",
            ),
        ),
    ]
