# Generated by Django 4.1.1 on 2022-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_alter_flight_origin_airport"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="is_origin",
            field=models.BooleanField(default=False),
        ),
    ]
