# Generated by Django 4.0.3 on 2022-11-30 03:05

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0005_alter_flight_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={
                "permissions": [
                    (
                        "status_registered_to_boarding_or_cancelled",
                        "Change status from registered to boarding or cancelled",
                    ),
                    (
                        "status_boarding_to_scheduled",
                        "Change status from boarding to scheduled",
                    ),
                    (
                        "status_scheduled_to_taxiing",
                        "Change status from scheduled to taxiing",
                    ),
                    ("status_taxiing_to_ready", "Change status from taxiing to ready"),
                    (
                        "status_ready_to_authorized",
                        "Change status from ready to authorized",
                    ),
                    (
                        "status_authorized_to_flying",
                        "Change status from authorized to flying",
                    ),
                    ("status_flying_to_landed", "Change status from flying to landed"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("registered", "Cadastrado"),
                    ("boarding", "Embarcando"),
                    ("cancelled", "Cancelado"),
                    ("scheduled", "Programado"),
                    ("taxiing", "Taxiando"),
                    ("ready", "Pronto"),
                    ("authorized", "Autorizado"),
                    ("flying", "Em voo"),
                    ("landed", "Aterrissado"),
                ],
                default="registered",
                max_length=50,
            ),
        ),
    ]
